const LANG = {
    "en": {
        "select" : "Select",
        "channel": "Channel",
        "start" : "Start",
        "broadcast": "Broadcast",
        "stop" : "Stop",
        "mute": "Mute",
        "unmute": "Unmute",
        "ok": "OK",
        "cancel": "Cancel",
        "show": "Show",
        "set password": "Set password",
        "unauthorised": "Unauthrorised"
    },
    "de" : {
        "select" : "Wählen",
        "channel": "Kanal",
        "start" : "Start",
        "broadcast": "Übertragung",
        "stop" : "Halt",
        "mute": "Stumm",
        "unmute": "Stimme",
        "ok": "OK",
        "cancel": "Abbrechen",
        "show": "Anzeigen",
        "set password": "Passwort festlegen",
        "unauthorised": "Unbefugt"
    },
    "es" : {
        "select" : "Seleccionar",
        "channel" : "Canal",
        "start" : "Comienzo",
        "broadcast": "Transmisión",
        "stop" : "Detener",
        "mute": "Mudo",
        "unmute": "Voz",
        "ok": "OK",
        "cancel": "Cancelar",
        "show": "Muestrar",
        "set password": "Configurar la clave",
        "unauthorised": "No autorizado"
    },
    "fr" : {
        "select" : "Sélectionnez",
        "channel" : "Chaîne",
        "start" : "Début",
        "broadcast": "Diffuser",
        "stop" : "Arrêtez",
        "mute": "Muet",
        "unmute": "Voix",
        "ok": "d'accord",
        "cancel": "Annuler",
        "show": "Montrer",
        "set password": "Définir le mot de passe",
        "unauthorised": "Non autorisé"
    },
    "hi" : {
        "select" : "चुनते हैं",
        "channel" : "चैनल",
        "start" : "प्रारंभ",
        "broadcast": "प्रसारण",
        "stop" : "रुकें",
        "mute": "मूक",
        "unmute": "अनम्यूट",
        "ok": "ठीक",
        "cancel": "रद्द करें",
        "show": "प्रदर्शन",
        "set password": "सांकेतिक शब्द लगना",
        "unauthorised": "अनधिकृत"
    },
    "nl" : {
        "select" : "Kiezen",
        "channel" : "Kanaal",
        "start" : "Begin",
        "broadcast": "Uitzending",
        "stop" : "Hou op",
        "mute": "Stom",
        "unmute": "Stem",
        "ok": "Oke",
        "cancel": "Annuleren",
        "show": "Laten zien",
        "set password": "Stel een wachtwoord in",
        "unauthorised": "ongeautoriseerd"
    },
    "pl" : {
        "select" : "Wybierz",
        "channel" : "Kanał",
        "start" : "Początek",
        "broadcast": "Audycja",
        "stop" : "Zatrzymać",
        "mute": "Niemy",
        "unmute": "Głos",
        "ok": "oK",
        "cancel": "Anulować",
        "show": "Pokazać",
        "set password": "Ustaw hasło",
        "unauthorised": "Nieautoryzowany"
    },
    "pt" : {
        "select" : "Selecione",
        "channel" : "Canal",
        "start" : "Começar",
        "broadcast": "Transmissão",
        "stop" : "Parar",
        "mute": "Sem som",
        "unmute": "Activar o som",
        "ok": "OK",
        "cancel": "Cancelar",
        "show": "Mostrar",
        "set password": "Configurar palavra-passe",
        "unauthorised": "Não autorizado"
    },
    "ta" : {
        "select" : "தேர்வு",
        "channel" : "சேனல்",
        "start" : "தொடக்கம்",
        "broadcast": "ஒளிபரப்பு",
        "stop" : "நிறுத்து",
        "mute": "முடக்கு",
        "unmute": "ஒலியடக்கவும்",
        "ok": "சரி",
        "cancel": "ரத்து செய்",
        "show": "காட்டு",
        "set password": "கடவுச்சொல்லை அமைக்கவும்",
        "unauthorised": "அங்கீகரிக்கப்படாதது"
    },
    "ru" : {
        "select" : "Выбрать",
        "channel": "канал",
        "start" : "Начните",
        "broadcast": "Транслировать",
        "stop" : "Стоп",
        "mute": "Немой",
        "unmute": "Голос",
        "ok": "Ok",
        "cancel": "Отмена",
        "show": "Показывать",
        "set password": "Установка пароля",
        "unauthorised": "Неавторизованный"
    }    
}

/*["af", "sq", "ar-SA", "ar-IQ", "ar-EG", "ar-LY", "ar-DZ", "ar-MA", "ar-TN", "ar-OM",
 "ar-YE", "ar-SY", "ar-JO", "ar-LB", "ar-KW", "ar-AE", "ar-BH", "ar-QA", "eu", "bg",
 "be", "ca", "zh-TW", "zh-CN", "zh-HK", "zh-SG", "hr", "cs", "da", "nl", "nl-BE", "en",
 "en-US", "en-EG", "en-AU", "en-GB", "en-CA", "en-NZ", "en-IE", "en-ZA", "en-JM",
 "en-BZ", "en-TT", "et", "fo", "fa", "fi", "fr", "fr-BE", "fr-CA", "fr-CH", "fr-LU",
 "gd", "gd-IE", "de", "de-CH", "de-AT", "de-LU", "de-LI", "el", "he", "hi", "hu", 
 "is", "id", "it", "it-CH", "ja", "ko", "lv", "lt", "mk", "mt", "no", "pl",
 "pt-BR", "pt", "rm", "ro", "ro-MO", "ru", "ru-MI", "sz", "sr", "sk", "sl", "sb",
 "es", "es-AR", "es-GT", "es-CR", "es-PA", "es-DO", "es-MX", "es-VE", "es-CO", 
 "es-PE", "es-EC", "es-CL", "es-UY", "es-PY", "es-BO", "es-SV", "es-HN", "es-NI", 
 "es-PR", "sx", "sv", "sv-FI", "th", "ts", "tn", "tr", "uk", "ur", "ve", "vi", "xh",
 "ji", "zu"];*/
